import bcrypt from "bcryptjs";
import type { Category, Database, Product, ProductVariant, Project, Spec, Subcategory, Unit } from "./types";

const now = "2026-09-27T00:00:00.000Z";

function category(
  slug: string,
  name: string,
  description: string,
  image: string,
  sortOrder: number,
): Category {
  return { id: slug, name, slug, description, image, sortOrder };
}

function sub(categoryId: string, slug: string, name: string, description = ""): Subcategory {
  return { id: `${categoryId}-${slug}`, categoryId, name, slug, description };
}

function product(partial: Product): Product {
  return partial;
}

function showroomItem(data: {
  id: string;
  name: string;
  slug: string;
  shortDescription: string;
  description: string;
  reference?: string | null;
  categoryId: string;
  subcategoryId: string;
  finish?: string | null;
  color?: string | null;
  format?: string | null;
  originCountry?: string | null;
  madeIn?: string | null;
  style?: string | null;
  usage?: string | null;
  unit?: Unit | null;
  images: { id: string; url: string; alt: string }[];
  variants?: ProductVariant[];
  technical: Spec[];
}): Product {
  return {
    id: data.id,
    name: data.name,
    slug: data.slug,
    shortDescription: data.shortDescription,
    description: data.description,
    reference: data.reference ?? null,
    categoryId: data.categoryId,
    subcategoryId: data.subcategoryId,
    brand: null,
    material: null,
    finish: data.finish ?? null,
    color: data.color ?? null,
    format: data.format ?? null,
    originCountry: data.originCountry ?? null,
    madeIn: data.madeIn ?? null,
    style: data.style ?? null,
    usage: data.usage ?? null,
    price: null,
    oldPrice: null,
    discount: null,
    currency: "TND",
    unit: data.unit ?? "piece",
    stock: null,
    stockStatus: "on_request",
    featured: true,
    newProduct: true,
    promotion: false,
    bestSeller: false,
    limitedStock: false,
    calculatorEnabled: data.unit === "m2",
    lossPercent: 10,
    published: true,
    seoTitle: `${data.name} | STE SANI-ESSEF`,
    seoDescription: data.shortDescription,
    seoKeywords: [data.name, data.reference, data.format, "sani-essef", "ksour essef"].filter(Boolean).join(", "),
    images: data.images.map((image, order) => ({ ...image, order })),
    variants: data.variants ?? [],
    technical: data.technical,
    extraInfo: "Prix, stock et caractéristiques non visibles sur l'image : information disponible sur demande.",
    views: 0,
    ordersCount: 0,
    createdAt: now,
    updatedAt: now,
  };
}

export async function createSeed(): Promise<Database> {
  const passwordHash = await bcrypt.hash(process.env.ADMIN_PASSWORD || "SaniEssef2026!", 10);

  const categories: Category[] = [
    category("carrelage", "Carrelage", "Sols et murs en grands formats, effets marbre, bois et pierre.", "/images/cat-carrelage.jpg", 1),
    category("salle-de-bain", "Salle de bain", "Douches, baignoires, receveurs et ensembles pour la salle d'eau.", "/images/cabine-91700.jpg", 2),
    category("sanitaires", "Sanitaires", "WC, lavabos et vasques pour des espaces nets et durables.", "/images/lavabo-bidet-stand.jpg", 3),
    category("robinetterie", "Robinetterie", "Mitigeurs et robinets au dessin contemporain.", "/images/cat-robinetterie.jpg", 4),
    category("meubles", "Meubles de salle de bain", "Meubles lavabo, colonnes et miroirs.", "/images/miroir-135099.jpg", 5),
    category("revetements-muraux", "Revêtements muraux", "Surfaces murales pour habiller un intérieur avec sobriété.", "/images/cat-mur.jpg", 6),
    category("revetements-sol", "Revêtements de sol", "Sols intérieurs au rendu pierre, bois ou minéral.", "/images/cat-sol.jpg", 7),
    category("decoration", "Décoration", "Pièces de caractère pour compléter un projet de rénovation.", "/images/carreau-decoratif.jpg", 8),
    category("accessoires", "Accessoires", "Porte-serviettes, distributeurs et accessoires de salle de bain.", "/images/cat-accessoires.jpg", 9),
  ];

  const subcategories: Subcategory[] = [
    sub("carrelage", "sol", "Carrelage sol"),
    sub("carrelage", "mur", "Carrelage mural"),
    sub("carrelage", "gres-cerame", "Grès cérame"),
    sub("carrelage", "semi-gres", "Semi-grès"),
    sub("carrelage", "effet-marbre", "Carrelage effet marbre"),
    sub("carrelage", "effet-bois", "Carrelage effet bois"),
    sub("carrelage", "effet-pierre", "Carrelage effet pierre"),
    sub("carrelage", "grand-format", "Grand format"),
    sub("carrelage", "interieur", "Carrelage intérieur"),
    sub("carrelage", "exterieur", "Carrelage extérieur"),
    sub("carrelage", "decoratif", "Carrelage décoratif"),
    sub("salle-de-bain", "wc", "WC"),
    sub("salle-de-bain", "lavabos", "Lavabos"),
    sub("salle-de-bain", "vasques", "Vasques"),
    sub("salle-de-bain", "douches", "Douches"),
    sub("salle-de-bain", "baignoires", "Baignoires"),
    sub("salle-de-bain", "parois", "Parois de douche"),
    sub("salle-de-bain", "receveurs", "Receveurs"),
    sub("salle-de-bain", "cabines", "Cabines de douche"),
    sub("sanitaires", "wc", "WC"),
    sub("sanitaires", "lavabos", "Lavabos"),
    sub("sanitaires", "vasques", "Vasques"),
    sub("robinetterie", "mitigeurs", "Mitigeurs"),
    sub("robinetterie", "lavabo", "Robinets lavabo"),
    sub("robinetterie", "douche", "Robinets douche"),
    sub("robinetterie", "baignoire", "Robinets baignoire"),
    sub("robinetterie", "accessoires", "Accessoires"),
    sub("meubles", "lavabo", "Meubles lavabo"),
    sub("meubles", "colonnes", "Colonnes"),
    sub("meubles", "miroirs", "Miroirs"),
    sub("meubles", "suspendus", "Meubles suspendus"),
    sub("revetements-muraux", "pierre", "Aspect pierre"),
    sub("revetements-muraux", "marbre", "Aspect marbre"),
    sub("revetements-sol", "bois", "Aspect bois"),
    sub("revetements-sol", "pierre", "Aspect pierre"),
    sub("decoration", "objets", "Objets"),
    sub("accessoires", "porte-serviettes", "Porte-serviettes"),
    sub("accessoires", "porte-savon", "Porte-savon"),
    sub("accessoires", "distributeurs", "Distributeurs"),
    sub("accessoires", "wc", "Accessoires WC"),
    sub("accessoires", "douche", "Accessoires douche"),
  ];

  const products: Product[] = [
    product({
      id: "tekalu-crema",
      name: "Tekalu Crema",
      slug: "tekalu-crema-120x60",
      shortDescription: "Revêtement crème, format 120 × 60 cm, finitions extra-poli et mat satiné.",
      description:
        "Tekalu Crema est un revêtement au ton crème élégant, proposé en format 120 × 60 cm. Sa finition extra-polie offre un aspect lumineux et sophistiqué, tandis que la finition mat satiné apporte une apparence plus douce et contemporaine.",
      reference: null,
      categoryId: "carrelage",
      subcategoryId: "carrelage-effet-marbre",
      brand: null,
      material: null,
      finish: "Extra-poli",
      color: "Crème / beige très clair",
      format: "120 × 60 cm",
      originCountry: "Espagne",
      madeIn: "Made in Spain",
      style: "Effet marbre",
      usage: null,
      price: 95,
      oldPrice: 120,
      discount: 21,
      currency: "TND",
      unit: "m2",
      stock: null,
      stockStatus: "on_request",
      featured: true,
      newProduct: true,
      promotion: true,
      bestSeller: false,
      limitedStock: false,
      calculatorEnabled: true,
      lossPercent: 10,
      published: true,
      seoTitle: "Tekalu Crema 120x60 | Carrelage effet marbre | STE SANI-ESSEF",
      seoDescription:
        "Tekalu Crema, format 120 × 60 cm, Made in Spain. Finitions extra-poli et mat satiné. Showroom STE SANI-ESSEF à Ksour Essef.",
      seoKeywords: "tekalu, crema, carrelage, marbre, beige, crème, 120x60, 120/60, espagne, salle de bain, tunisie, ksour essef",
      images: [
        { id: "tc0", url: "/images/tekalu-slabs.jpg", alt: "Tekalu Crema 120 × 60, extra-poli et mat satiné", order: 0 },
        { id: "tc1", url: "/images/tekalu-1.jpg", alt: "Tekalu Crema, aspect pierre clair", order: 1 },
        { id: "tc2", url: "/images/tekalu-2.jpg", alt: "Surface crème veinée", order: 2 },
        { id: "tc3", url: "/images/tekalu-3.jpg", alt: "Ambiance intérieure claire", order: 3 },
      ],
      variants: [
        { id: "tc-poli", name: "Extra-poli", finish: "Extra-poli", price: null },
        { id: "tc-mat", name: "Mat satiné", finish: "Mat satiné", price: null },
      ],
      technical: [
        { label: "Format", value: "120 × 60 cm" },
        { label: "Origine", value: "Espagne" },
        { label: "Pays", value: "Made in Spain" },
        { label: "Finitions visibles", value: "Extra-poli, Mat satiné" },
        { label: "Couleur", value: "Crème / beige très clair" },
        { label: "Aspect", value: "Pierre / marbre clair avec veinage subtil" },
      ],
      extraInfo:
        "Description indicative, non présentée comme fiche technique officielle. Épaisseur, résistance, classement, matière exacte et prix : information disponible sur demande.",
      views: 0,
      ordersCount: 0,
      createdAt: now,
      updatedAt: now,
    }),
    product({
      id: "semi-gres-28005",
      name: "Produit semi-grès - Référence 28005",
      slug: "semi-gres-28005-20x80",
      shortDescription: "Revêtement effet bois clair, format 20 × 80 cm, référence 28005.",
      description:
        "Revêtement au style bois naturel, adapté à la création d'intérieurs chaleureux et contemporains. Son format 20 × 80 cm permet différentes compositions de pose.",
      reference: "28005",
      categoryId: "carrelage",
      subcategoryId: "carrelage-semi-gres",
      brand: null,
      material: null,
      finish: "Semi-grès",
      color: "Bois clair / beige",
      format: "20 × 80 cm",
      originCountry: null,
      madeIn: null,
      style: "Effet bois",
      usage: "Revêtement de sol intérieur",
      price: 48,
      oldPrice: null,
      discount: null,
      currency: "TND",
      unit: "m2",
      stock: null,
      stockStatus: "on_request",
      featured: true,
      newProduct: true,
      promotion: false,
      bestSeller: false,
      limitedStock: false,
      calculatorEnabled: true,
      lossPercent: 10,
      published: true,
      seoTitle: "Semi-grès effet bois 20x80 référence 28005 | STE SANI-ESSEF",
      seoDescription:
        "Revêtement semi-grès effet bois, format 20 × 80 cm, référence 28005. Sol intérieur. STE SANI-ESSEF, Ksour Essef.",
      seoKeywords: "28005, semi-grès, semi gres, carrelage bois, bois clair, beige, 20x80, 20/80, sol, tunisie",
      images: [
        { id: "sg1", url: "/images/bois-clair-1.jpg", alt: "Revêtement effet bois clair", order: 0 },
        { id: "sg2", url: "/images/bois-clair-2.jpg", alt: "Pose effet bois intérieur", order: 1 },
      ],
      variants: [],
      technical: [
        { label: "Format", value: "20 × 80 cm" },
        { label: "Référence", value: "28005" },
        { label: "Finition", value: "Semi-grès" },
        { label: "Style", value: "Effet bois" },
        { label: "Couleur", value: "Bois clair / beige" },
        { label: "Utilisation visible", value: "Revêtement de sol intérieur" },
      ],
      extraInfo:
        "Épaisseur, résistance, classement, prix, matière exacte et quantité par carton : information disponible sur demande.",
      views: 0,
      ordersCount: 0,
      createdAt: now,
      updatedAt: now,
    }),
    product({
      id: "coster-wood",
      name: "Coster Wood",
      slug: "coster-wood-120x60",
      shortDescription: "Collection effet bois naturel, format 120 × 60 cm, Made in India.",
      description:
        "Collection Coster Wood au rendu bois naturel, pensée pour apporter une atmosphère chaleureuse et élégante aux espaces intérieurs.",
      reference: null,
      categoryId: "carrelage",
      subcategoryId: "carrelage-effet-bois",
      brand: null,
      material: null,
      finish: null,
      color: "Brun / bois naturel",
      format: "120 × 60 cm",
      originCountry: "Inde",
      madeIn: "Made in India",
      style: "Effet bois",
      usage: null,
      price: 79,
      oldPrice: null,
      discount: null,
      currency: "TND",
      unit: "m2",
      stock: null,
      stockStatus: "on_request",
      featured: true,
      newProduct: true,
      promotion: false,
      bestSeller: false,
      limitedStock: false,
      calculatorEnabled: true,
      lossPercent: 10,
      published: true,
      seoTitle: "Coster Wood 120x60 | Carrelage effet bois | STE SANI-ESSEF",
      seoDescription:
        "Coster Wood, format 120 × 60 cm, Made in India. Rendu bois naturel. Showroom STE SANI-ESSEF à Ksour Essef.",
      seoKeywords: "coster, wood, carrelage bois, effet bois, brun, 120x60, 120/60, inde, tunisie, mahdia",
      images: [
        { id: "cw1", url: "/images/coster-1.jpg", alt: "Coster Wood, rendu bois naturel", order: 0 },
        { id: "cw2", url: "/images/coster-2.jpg", alt: "Ambiance bois chaleureuse", order: 1 },
      ],
      variants: [],
      technical: [
        { label: "Format", value: "120 × 60 cm" },
        { label: "Origine", value: "Inde" },
        { label: "Pays", value: "Made in India" },
        { label: "Aspect", value: "Bois naturel" },
        { label: "Couleur", value: "Brun / bois naturel" },
        { label: "Style", value: "Effet bois" },
      ],
      extraInfo: "Référence, finition, matière, épaisseur et prix : information disponible sur demande.",
      views: 0,
      ordersCount: 0,
      createdAt: now,
      updatedAt: now,
    }),
    showroomItem({
      id: "black-portoro",
      name: "Black Portoro",
      slug: "black-portoro-120x60",
      shortDescription: "Revêtement noir veiné or, format 120 × 60 cm, Made in India.",
      description: "Black Portoro, format 120 × 60 cm, au veinage clair sur fond noir. Made in India.",
      categoryId: "carrelage",
      subcategoryId: "carrelage-effet-marbre",
      color: "Noir / veinage or",
      format: "120 × 60 cm",
      originCountry: "Inde",
      madeIn: "Made in India",
      style: "Effet marbre",
      unit: "m2",
      images: [{ id: "bp1", url: "/images/black-portoro.jpg", alt: "Black Portoro 120 × 60, Made in India" }],
      technical: [
        { label: "Format", value: "120 × 60 cm" },
        { label: "Pays", value: "Made in India" },
        { label: "Couleur visible", value: "Noir veiné" },
      ],
    }),
    showroomItem({
      id: "sidi-bousaid",
      name: "Sidi Bou Saïd",
      slug: "sidi-bousaid-15x15",
      shortDescription: "Carreau décoratif 15 × 15 cm, référence GDM 150013.",
      description: "Collection Sidi Bou Saïd, format 15 × 15 cm, motifs bleus et blancs. Référence GDM 150013.",
      reference: "GDM 150013",
      categoryId: "carrelage",
      subcategoryId: "carrelage-decoratif",
      color: "Bleu / blanc",
      format: "15 × 15 cm",
      style: "Décoratif",
      unit: "m2",
      images: [{ id: "sb1", url: "/images/sidi-bousaid.jpg", alt: "Carreaux Sidi Bou Saïd 15 × 15" }],
      technical: [
        { label: "Format", value: "15 × 15 cm" },
        { label: "Référence", value: "GDM 150013" },
      ],
    }),
    showroomItem({
      id: "hammamet",
      name: "Hammamet",
      slug: "hammamet-15x15",
      shortDescription: "Carreau décoratif 15 × 15 cm, référence GSM 150227.",
      description: "Collection Hammamet, format 15 × 15 cm. Référence GSM 150227.",
      reference: "GSM 150227",
      categoryId: "carrelage",
      subcategoryId: "carrelage-decoratif",
      color: "Bleu / blanc",
      format: "15 × 15 cm",
      style: "Décoratif",
      unit: "m2",
      images: [{ id: "hm1", url: "/images/hammamet.jpg", alt: "Carreaux Hammamet 15 × 15" }],
      technical: [
        { label: "Format", value: "15 × 15 cm" },
        { label: "Référence", value: "GSM 150227" },
      ],
    }),
    showroomItem({
      id: "leptis",
      name: "Leptis",
      slug: "leptis-15x15",
      shortDescription: "Carreau décoratif 15 × 15 cm, référence GSM 150229.",
      description: "Collection Leptis, format 15 × 15 cm. Référence GSM 150229.",
      reference: "GSM 150229",
      categoryId: "carrelage",
      subcategoryId: "carrelage-decoratif",
      color: "Bleu / jaune",
      format: "15 × 15 cm",
      style: "Décoratif",
      unit: "m2",
      images: [{ id: "lp1", url: "/images/leptis.jpg", alt: "Carreaux Leptis 15 × 15" }],
      technical: [
        { label: "Format", value: "15 × 15 cm" },
        { label: "Référence", value: "GSM 150229" },
      ],
    }),
    showroomItem({
      id: "takrouna-gris",
      name: "Takrouna Gris",
      slug: "takrouna-gris-15x15",
      shortDescription: "Carreau décoratif 15 × 15 cm, référence GSM 150330.",
      description: "Collection Takrouna Gris, format 15 × 15 cm. Référence GSM 150330.",
      reference: "GSM 150330",
      categoryId: "carrelage",
      subcategoryId: "carrelage-decoratif",
      color: "Gris",
      format: "15 × 15 cm",
      style: "Décoratif",
      unit: "m2",
      images: [{ id: "tk1", url: "/images/takrouna-gris.jpg", alt: "Carreaux Takrouna Gris 15 × 15" }],
      technical: [
        { label: "Format", value: "15 × 15 cm" },
        { label: "Référence", value: "GSM 150330" },
      ],
    }),
    showroomItem({
      id: "kairouan",
      name: "Kairouan",
      slug: "kairouan-15x15",
      shortDescription: "Carreau décoratif 15 × 15 cm, référence GSM 150244.",
      description: "Collection Kairouan, format 15 × 15 cm. Référence GSM 150244.",
      reference: "GSM 150244",
      categoryId: "carrelage",
      subcategoryId: "carrelage-decoratif",
      color: "Vert / blanc",
      format: "15 × 15 cm",
      style: "Décoratif",
      unit: "m2",
      images: [{ id: "kr1", url: "/images/kairouan.jpg", alt: "Carreaux Kairouan 15 × 15" }],
      technical: [
        { label: "Format", value: "15 × 15 cm" },
        { label: "Référence", value: "GSM 150244" },
      ],
    }),
    showroomItem({
      id: "miroir-135099",
      name: "Miroir LED 60 × 80",
      slug: "miroir-led-60x80-135099",
      shortDescription: "Miroir 60 × 80, LED et antifog. Référence 135099.",
      description: "Miroir 60 × 80 avec LED et antifog. Référence 135099.",
      reference: "135099",
      categoryId: "meubles",
      subcategoryId: "meubles-miroirs",
      format: "60 × 80 cm",
      style: "LED",
      usage: "Salle de bain",
      images: [{ id: "m135099", url: "/images/miroir-135099.jpg", alt: "Miroir LED 60 × 80, référence 135099" }],
      technical: [
        { label: "Format", value: "60 × 80 cm" },
        { label: "Référence", value: "135099" },
        { label: "Visible", value: "LED, antifog" },
      ],
    }),
    showroomItem({
      id: "miroir-134844",
      name: "Miroir LED 70 × 70",
      slug: "miroir-led-70x70-134844",
      shortDescription: "Miroir rond 70 × 70, LED, antifog et horloge. Référence 134844.",
      description: "Miroir 70 × 70 avec LED, antifog et horloge. Référence 134844.",
      reference: "134844",
      categoryId: "meubles",
      subcategoryId: "meubles-miroirs",
      format: "70 × 70 cm",
      style: "LED",
      usage: "Salle de bain",
      images: [{ id: "m134844", url: "/images/miroir-134844.jpg", alt: "Miroir LED rond 70 × 70, référence 134844" }],
      technical: [
        { label: "Format", value: "70 × 70 cm" },
        { label: "Référence", value: "134844" },
        { label: "Visible", value: "LED, antifog, horloge" },
      ],
    }),
    showroomItem({
      id: "miroir-134933",
      name: "Miroir LED silver 60 × 80",
      slug: "miroir-led-silver-60x80-134933",
      shortDescription: "Miroir ovale 60 × 80, LED et antifog silver. Référence 134933.",
      description: "Miroir 60 × 80, LED et antifog silver. Référence 134933.",
      reference: "134933",
      categoryId: "meubles",
      subcategoryId: "meubles-miroirs",
      format: "60 × 80 cm",
      finish: "Silver",
      style: "LED",
      usage: "Salle de bain",
      images: [{ id: "m134933", url: "/images/miroir-134933.jpg", alt: "Miroir LED silver 60 × 80, référence 134933" }],
      technical: [
        { label: "Format", value: "60 × 80 cm" },
        { label: "Référence", value: "134933" },
        { label: "Visible", value: "LED, antifog silver" },
      ],
    }),
    showroomItem({
      id: "miroir-134911",
      name: "Miroir LED black 45 × 100",
      slug: "miroir-led-black-45x100-134911",
      shortDescription: "Miroir 45 × 100, LED black, antifog et horloge. Référence 134911.",
      description: "Miroir 45 × 100, LED black, antifog et horloge. Référence 134911.",
      reference: "134911",
      categoryId: "meubles",
      subcategoryId: "meubles-miroirs",
      format: "45 × 100 cm",
      finish: "Black",
      style: "LED",
      usage: "Salle de bain",
      images: [{ id: "m134911", url: "/images/miroir-134911.jpg", alt: "Miroir LED black 45 × 100, référence 134911" }],
      technical: [
        { label: "Format", value: "45 × 100 cm" },
        { label: "Référence", value: "134911" },
        { label: "Visible", value: "LED black, antifog, horloge" },
      ],
    }),
    showroomItem({
      id: "cabine-91700",
      name: "Cabine de douche 90 × 90 coin",
      slug: "cabine-douche-90x90-91700",
      shortDescription: "Cabine de douche d'angle 90 × 90. Référence 91700.",
      description: "Cabine de douche d'angle, format 90 × 90. Référence 91700.",
      reference: "91700",
      categoryId: "salle-de-bain",
      subcategoryId: "salle-de-bain-cabines",
      format: "90 × 90 cm",
      style: "Coin",
      usage: "Douche",
      images: [{ id: "c91700", url: "/images/cabine-91700.jpg", alt: "Cabine de douche 90 × 90 coin, référence 91700" }],
      technical: [
        { label: "Format", value: "90 × 90 cm" },
        { label: "Référence", value: "91700" },
        { label: "Type visible", value: "Coin" },
      ],
    }),
    showroomItem({
      id: "cabine-114944",
      name: "Cabine de douche 90 × 90 black",
      slug: "cabine-douche-90x90-black-114944",
      shortDescription: "Cabine d'angle 90 × 90, profilé noir, verre. Référence 114944.",
      description: "Cabine de douche d'angle 90 × 90, profilé noir. Référence 114944.",
      reference: "114944",
      categoryId: "salle-de-bain",
      subcategoryId: "salle-de-bain-cabines",
      format: "90 × 90 cm",
      finish: "Black",
      color: "Noir",
      style: "Coin",
      usage: "Douche",
      images: [{ id: "c114944", url: "/images/cabine-114944.jpg", alt: "Cabine de douche 90 × 90 black, référence 114944" }],
      technical: [
        { label: "Format", value: "90 × 90 cm" },
        { label: "Référence", value: "114944" },
        { label: "Visible", value: "Coin, profilé noir, verre" },
      ],
    }),
    showroomItem({
      id: "cabine-117588",
      name: "Cabine de douche Bella 120 × 80 black",
      slug: "cabine-douche-bella-120x80-117588",
      shortDescription: "Cabine Bella 120 × 80, profilé noir. Référence 117588.",
      description: "Cabine de douche Bella, format 120 × 80, profilé noir. Référence 117588.",
      reference: "117588",
      categoryId: "salle-de-bain",
      subcategoryId: "salle-de-bain-cabines",
      format: "120 × 80 cm",
      finish: "Black",
      color: "Noir",
      style: "Bella",
      usage: "Douche",
      images: [{ id: "c117588", url: "/images/cabine-117588.jpg", alt: "Cabine Bella 120 × 80 black, référence 117588" }],
      technical: [
        { label: "Format", value: "120 × 80 cm" },
        { label: "Référence", value: "117588" },
        { label: "Visible", value: "Bella, profilé noir" },
      ],
    }),
    showroomItem({
      id: "cabine-119888",
      name: "Cabine de douche Babel 80 × 80",
      slug: "cabine-douche-babel-80x80-119888",
      shortDescription: "Cabine d'angle 80 × 80 chromée, collection Babel. Référence 119888.",
      description: "Cabine de douche d'angle 80 × 80, finition chromée, collection Babel. Référence 119888.",
      reference: "119888",
      categoryId: "salle-de-bain",
      subcategoryId: "salle-de-bain-cabines",
      format: "80 × 80 cm",
      finish: "Chromée",
      style: "Babel",
      usage: "Douche",
      images: [{ id: "c119888", url: "/images/cabine-119888.jpg", alt: "Cabine Babel 80 × 80 chromée, référence 119888" }],
      technical: [
        { label: "Format", value: "80 × 80 cm" },
        { label: "Référence", value: "119888" },
        { label: "Visible", value: "Coin, chromée, Babel" },
      ],
    }),
    showroomItem({
      id: "cabine-carree-black",
      name: "Cabine de douche carrée black",
      slug: "cabine-douche-carree-black",
      shortDescription: "Cabine carrée, profilé noir, verre. Formats 80 × 80 et 90 × 90.",
      description: "Cabine de douche carrée, profilé noir et verre. Formats visibles : 80 × 80 (réf. 98700) et 90 × 90 (réf. 104330).",
      categoryId: "salle-de-bain",
      subcategoryId: "salle-de-bain-cabines",
      format: "80 × 80 / 90 × 90 cm",
      finish: "Black",
      color: "Noir",
      style: "Carrée",
      usage: "Douche",
      images: [{ id: "ccb1", url: "/images/cabine-carree-black.jpg", alt: "Cabine de douche carrée black 80 × 80 et 90 × 90" }],
      variants: [
        { id: "ccb-80", name: "80 × 80 · réf. 98700", finish: "Black", price: null },
        { id: "ccb-90", name: "90 × 90 · réf. 104330", finish: "Black", price: null },
      ],
      technical: [
        { label: "Formats visibles", value: "80 × 80 cm, 90 × 90 cm" },
        { label: "Références", value: "98700, 104330" },
        { label: "Visible", value: "Carrée, profilé noir, verre" },
      ],
    }),
    showroomItem({
      id: "lavabo-bidet-stand",
      name: "Lavabo-bidet sur pied",
      slug: "lavabo-bidet-stand",
      shortDescription: "Lavabo-bidet 2 en 1 sur pied, importé, avec robinetterie. Blanc brillant ou noir mat.",
      description: "Lavabo-bidet sur pied, 2 en 1, importé, avec robinetterie et accessoires. Finitions visibles : blanc brillant et noir mat.",
      categoryId: "sanitaires",
      subcategoryId: "sanitaires-lavabos",
      finish: "Céramique",
      style: "Sur pied",
      usage: "Lavabo",
      images: [
        { id: "lb1", url: "/images/lavabo-bidet-stand.jpg", alt: "Lavabo-bidet sur pied blanc brillant et noir mat" },
        { id: "lb2", url: "/images/lavabo-bidet-stand-2.jpg", alt: "Lavabo-bidet sur pied, deux finitions" },
      ],
      variants: [
        { id: "lb-blanc", name: "Blanc brillant", finish: "Blanc brillant", price: null },
        { id: "lb-noir", name: "Noir mat", finish: "Noir mat", price: null },
      ],
      technical: [
        { label: "Type visible", value: "Lavabo-bidet 2 en 1, sur pied" },
        { label: "Finitions visibles", value: "Blanc brillant, noir mat" },
        { label: "Inclus visible", value: "Robinetterie et accessoires" },
      ],
    }),
    showroomItem({
      id: "lavabos-pied",
      name: "Lavabos sur pied céramique",
      slug: "lavabos-sur-pied-ceramique",
      shortDescription: "Lavabos sur pied en céramique, plusieurs formes et finitions.",
      description: "Lavabos sur pied en céramique, présentés en plusieurs silhouettes : blancs, noir, facettés ou lisses.",
      categoryId: "sanitaires",
      subcategoryId: "sanitaires-lavabos",
      finish: "Céramique",
      style: "Sur pied",
      usage: "Lavabo",
      images: [{ id: "lpied1", url: "/images/lavabos-pied.jpg", alt: "Lavabos sur pied en céramique" }],
      technical: [
        { label: "Matière visible", value: "Céramique" },
        { label: "Type visible", value: "Sur pied" },
      ],
    }),
  ];

  const projects: Project[] = [
    {
      id: "p-marbre",
      title: "Sol effet marbre",
      slug: "sol-effet-marbre",
      room: "Sol",
      description: "Une surface claire, presque minérale, qui agrandit la pièce et capte la lumière.",
      image: "/images/project-marbre.jpg",
      productIds: ["tekalu-crema"],
      published: true,
      sortOrder: 1,
      createdAt: now,
    },
    {
      id: "p-bois",
      title: "Sol effet bois",
      slug: "sol-effet-bois",
      room: "Sol",
      description: "Le rythme des lames bois réchauffe un intérieur contemporain sans alourdir les volumes.",
      image: "/images/project-bois.jpg",
      productIds: ["coster-wood", "semi-gres-28005"],
      published: true,
      sortOrder: 2,
      createdAt: now,
    },
    {
      id: "p-bain",
      title: "Salle de bain",
      slug: "salle-de-bain",
      room: "Salle de bain",
      description: "Matières claires, lignes simples, une salle d'eau pensée comme une pièce à vivre.",
      image: "/images/project-bain.jpg",
      productIds: ["tekalu-crema"],
      published: true,
      sortOrder: 3,
      createdAt: now,
    },
    {
      id: "p-salon",
      title: "Salon",
      slug: "salon",
      room: "Salon",
      description: "Un sol continu et une palette sable pour laisser le mobilier respirer.",
      image: "/images/project-salon.jpg",
      productIds: ["tekalu-crema"],
      published: true,
      sortOrder: 4,
      createdAt: now,
    },
    {
      id: "p-chambre",
      title: "Chambre",
      slug: "chambre",
      room: "Chambre",
      description: "Une atmosphère feutrée, portée par des tons bois et une lumière douce.",
      image: "/images/project-chambre.jpg",
      productIds: ["coster-wood"],
      published: true,
      sortOrder: 5,
      createdAt: now,
    },
    {
      id: "p-cuisine",
      title: "Cuisine",
      slug: "cuisine",
      room: "Cuisine",
      description: "Des surfaces faciles à vivre, dans une cuisine claire et graphique.",
      image: "/images/project-cuisine.jpg",
      productIds: ["tekalu-crema"],
      published: true,
      sortOrder: 6,
      createdAt: now,
    },
    {
      id: "p-terrasse",
      title: "Terrasse",
      slug: "terrasse",
      room: "Terrasse",
      description: "Prolonger l'intérieur vers l'extérieur avec une matière minérale.",
      image: "/images/project-terrasse.jpg",
      productIds: [],
      published: true,
      sortOrder: 7,
      createdAt: now,
    },
    {
      id: "p-entree",
      title: "Entrée",
      slug: "entree",
      room: "Entrée",
      description: "Le premier geste de la maison : un sol net, un ton chaud, une impression d'ordre.",
      image: "/images/project-entree.jpg",
      productIds: ["semi-gres-28005"],
      published: true,
      sortOrder: 8,
      createdAt: now,
    },
    {
      id: "p-mur",
      title: "Mur décoratif",
      slug: "mur-decoratif",
      room: "Mur",
      description: "Un mur traité comme une matière, pour structurer un salon ou une salle de bain.",
      image: "/images/project-mur.jpg",
      productIds: ["tekalu-crema"],
      published: true,
      sortOrder: 9,
      createdAt: now,
    },
  ];

  return {
    users: [
      {
        id: "admin",
        email: (process.env.ADMIN_EMAIL || "admin@sani-essef.tn").toLowerCase(),
        passwordHash,
        firstName: "Admin",
        lastName: "SANI-ESSEF",
        phone: "73 664 229",
        role: "admin",
        createdAt: now,
      },
    ],
    categories,
    subcategories,
    products,
    customers: [],
    orders: [],
    quotes: [],
    reviews: [],
    messages: [],
    projects,
    banners: [
      {
        id: "hero",
        title: "Donnez une nouvelle dimension à votre intérieur",
        subtitle: "Découvrez notre sélection de carrelages, revêtements et solutions pour embellir votre maison.",
        eyebrow: "Qualité • Design • Innovation • Rénovation",
        image: "/images/hero.jpg",
        ctaLabel: "Découvrir nos produits",
        ctaHref: "/shop",
        secondaryLabel: "Demander un devis",
        secondaryHref: "/quote",
        active: true,
        sortOrder: 1,
      },
    ],
    settings: {
      phone: "73 664 229",
      phoneTel: "+21673664229",
      gsm: "26 416 564",
      gsmTel: "+21626416564",
      whatsapp: "21626416564",
      address: "Route de Mahdia, Ksour Essef, Tunisie",
      hours: "08:00 - 18:30",
      days: "Ouvert 7/7",
      slogan: "Ça donne envie de rénover",
      facebook: "",
      instagram: "",
      email: "",
    },
  };
}
