import bcrypt from "bcryptjs";
import type { Category, Database, Product, Project, Subcategory } from "./types";

const now = "2026-09-27T00:00:00.000Z";

function category(
  slug: string,
  name: string,
  description: string,
  image: string,
  sortOrder: number,
): Category {
  return { id: slug, name, slug, description, image, sortOrder };
}

function sub(categoryId: string, slug: string, name: string, description = ""): Subcategory {
  return { id: `${categoryId}-${slug}`, categoryId, name, slug, description };
}

function product(partial: Product): Product {
  return partial;
}

export async function createSeed(): Promise<Database> {
  const passwordHash = await bcrypt.hash(process.env.ADMIN_PASSWORD || "SaniEssef2026!", 10);

  const categories: Category[] = [
    category("carrelage", "Carrelage", "Sols et murs en grands formats, effets marbre, bois et pierre.", "/images/cat-carrelage.jpg", 1),
    category("salle-de-bain", "Salle de bain", "Douches, baignoires, receveurs et ensembles pour la salle d'eau.", "/images/cat-bain.jpg", 2),
    category("sanitaires", "Sanitaires", "WC, lavabos et vasques pour des espaces nets et durables.", "/images/cat-sanitaires.jpg", 3),
    category("robinetterie", "Robinetterie", "Mitigeurs et robinets au dessin contemporain.", "/images/cat-robinetterie.jpg", 4),
    category("meubles", "Meubles de salle de bain", "Meubles lavabo, colonnes et miroirs.", "/images/cat-meubles.jpg", 5),
    category("revetements-muraux", "Revêtements muraux", "Surfaces murales pour habiller un intérieur avec sobriété.", "/images/cat-mur.jpg", 6),
    category("revetements-sol", "Revêtements de sol", "Sols intérieurs au rendu pierre, bois ou minéral.", "/images/cat-sol.jpg", 7),
    category("decoration", "Décoration", "Pièces de caractère pour compléter un projet de rénovation.", "/images/cat-decor.jpg", 8),
    category("accessoires", "Accessoires", "Porte-serviettes, distributeurs et accessoires de salle de bain.", "/images/cat-accessoires.jpg", 9),
  ];

  const subcategories: Subcategory[] = [
    sub("carrelage", "sol", "Carrelage sol"),
    sub("carrelage", "mur", "Carrelage mural"),
    sub("carrelage", "gres-cerame", "Grès cérame"),
    sub("carrelage", "semi-gres", "Semi-grès"),
    sub("carrelage", "effet-marbre", "Carrelage effet marbre"),
    sub("carrelage", "effet-bois", "Carrelage effet bois"),
    sub("carrelage", "effet-pierre", "Carrelage effet pierre"),
    sub("carrelage", "grand-format", "Grand format"),
    sub("carrelage", "interieur", "Carrelage intérieur"),
    sub("carrelage", "exterieur", "Carrelage extérieur"),
    sub("salle-de-bain", "wc", "WC"),
    sub("salle-de-bain", "lavabos", "Lavabos"),
    sub("salle-de-bain", "vasques", "Vasques"),
    sub("salle-de-bain", "douches", "Douches"),
    sub("salle-de-bain", "baignoires", "Baignoires"),
    sub("salle-de-bain", "parois", "Parois de douche"),
    sub("salle-de-bain", "receveurs", "Receveurs"),
    sub("sanitaires", "wc", "WC"),
    sub("sanitaires", "lavabos", "Lavabos"),
    sub("sanitaires", "vasques", "Vasques"),
    sub("robinetterie", "mitigeurs", "Mitigeurs"),
    sub("robinetterie", "lavabo", "Robinets lavabo"),
    sub("robinetterie", "douche", "Robinets douche"),
    sub("robinetterie", "baignoire", "Robinets baignoire"),
    sub("robinetterie", "accessoires", "Accessoires"),
    sub("meubles", "lavabo", "Meubles lavabo"),
    sub("meubles", "colonnes", "Colonnes"),
    sub("meubles", "miroirs", "Miroirs"),
    sub("meubles", "suspendus", "Meubles suspendus"),
    sub("revetements-muraux", "pierre", "Aspect pierre"),
    sub("revetements-muraux", "marbre", "Aspect marbre"),
    sub("revetements-sol", "bois", "Aspect bois"),
    sub("revetements-sol", "pierre", "Aspect pierre"),
    sub("decoration", "objets", "Objets"),
    sub("accessoires", "porte-serviettes", "Porte-serviettes"),
    sub("accessoires", "porte-savon", "Porte-savon"),
    sub("accessoires", "distributeurs", "Distributeurs"),
    sub("accessoires", "wc", "Accessoires WC"),
    sub("accessoires", "douche", "Accessoires douche"),
  ];

  const products: Product[] = [
    product({
      id: "tekalu-crema",
      name: "Tekalu Crema",
      slug: "tekalu-crema-120x60",
      shortDescription: "Revêtement crème, format 120 × 60 cm, finitions extra-poli et mat satiné.",
      description:
        "Tekalu Crema est un revêtement au ton crème élégant, proposé en format 120 × 60 cm. Sa finition extra-polie offre un aspect lumineux et sophistiqué, tandis que la finition mat satiné apporte une apparence plus douce et contemporaine.",
      reference: null,
      categoryId: "carrelage",
      subcategoryId: "carrelage-effet-marbre",
      brand: null,
      material: null,
      finish: "Extra-poli",
      color: "Crème / beige très clair",
      format: "120 × 60 cm",
      originCountry: "Espagne",
      madeIn: "Made in Spain",
      style: "Effet marbre",
      usage: null,
      price: 95,
      oldPrice: 120,
      discount: 21,
      currency: "TND",
      unit: "m2",
      stock: null,
      stockStatus: "on_request",
      featured: true,
      newProduct: true,
      promotion: true,
      bestSeller: false,
      limitedStock: false,
      calculatorEnabled: true,
      lossPercent: 10,
      published: true,
      seoTitle: "Tekalu Crema 120x60 | Carrelage effet marbre | STE SANI-ESSEF",
      seoDescription:
        "Tekalu Crema, format 120 × 60 cm, Made in Spain. Finitions extra-poli et mat satiné. Showroom STE SANI-ESSEF à Ksour Essef.",
      seoKeywords: "tekalu, crema, carrelage, marbre, beige, crème, 120x60, 120/60, espagne, salle de bain, tunisie, ksour essef",
      images: [
        { id: "tc1", url: "/images/tekalu-1.jpg", alt: "Tekalu Crema, aspect pierre clair", order: 0 },
        { id: "tc2", url: "/images/tekalu-2.jpg", alt: "Surface crème veinée", order: 1 },
        { id: "tc3", url: "/images/tekalu-3.jpg", alt: "Ambiance intérieure claire", order: 2 },
      ],
      variants: [
        { id: "tc-poli", name: "Extra-poli", finish: "Extra-poli", price: null },
        { id: "tc-mat", name: "Mat satiné", finish: "Mat satiné", price: null },
      ],
      technical: [
        { label: "Format", value: "120 × 60 cm" },
        { label: "Origine", value: "Espagne" },
        { label: "Pays", value: "Made in Spain" },
        { label: "Finitions visibles", value: "Extra-poli, Mat satiné" },
        { label: "Couleur", value: "Crème / beige très clair" },
        { label: "Aspect", value: "Pierre / marbre clair avec veinage subtil" },
      ],
      extraInfo:
        "Description indicative, non présentée comme fiche technique officielle. Épaisseur, résistance, classement, matière exacte et prix : information disponible sur demande.",
      views: 0,
      ordersCount: 0,
      createdAt: now,
      updatedAt: now,
    }),
    product({
      id: "semi-gres-28005",
      name: "Produit semi-grès - Référence 28005",
      slug: "semi-gres-28005-20x80",
      shortDescription: "Revêtement effet bois clair, format 20 × 80 cm, référence 28005.",
      description:
        "Revêtement au style bois naturel, adapté à la création d'intérieurs chaleureux et contemporains. Son format 20 × 80 cm permet différentes compositions de pose.",
      reference: "28005",
      categoryId: "carrelage",
      subcategoryId: "carrelage-semi-gres",
      brand: null,
      material: null,
      finish: "Semi-grès",
      color: "Bois clair / beige",
      format: "20 × 80 cm",
      originCountry: null,
      madeIn: null,
      style: "Effet bois",
      usage: "Revêtement de sol intérieur",
      price: 48,
      oldPrice: null,
      discount: null,
      currency: "TND",
      unit: "m2",
      stock: null,
      stockStatus: "on_request",
      featured: true,
      newProduct: true,
      promotion: false,
      bestSeller: false,
      limitedStock: false,
      calculatorEnabled: true,
      lossPercent: 10,
      published: true,
      seoTitle: "Semi-grès effet bois 20x80 référence 28005 | STE SANI-ESSEF",
      seoDescription:
        "Revêtement semi-grès effet bois, format 20 × 80 cm, référence 28005. Sol intérieur. STE SANI-ESSEF, Ksour Essef.",
      seoKeywords: "28005, semi-grès, semi gres, carrelage bois, bois clair, beige, 20x80, 20/80, sol, tunisie",
      images: [
        { id: "sg1", url: "/images/bois-clair-1.jpg", alt: "Revêtement effet bois clair", order: 0 },
        { id: "sg2", url: "/images/bois-clair-2.jpg", alt: "Pose effet bois intérieur", order: 1 },
      ],
      variants: [],
      technical: [
        { label: "Format", value: "20 × 80 cm" },
        { label: "Référence", value: "28005" },
        { label: "Finition", value: "Semi-grès" },
        { label: "Style", value: "Effet bois" },
        { label: "Couleur", value: "Bois clair / beige" },
        { label: "Utilisation visible", value: "Revêtement de sol intérieur" },
      ],
      extraInfo:
        "Épaisseur, résistance, classement, prix, matière exacte et quantité par carton : information disponible sur demande.",
      views: 0,
      ordersCount: 0,
      createdAt: now,
      updatedAt: now,
    }),
    product({
      id: "coster-wood",
      name: "Coster Wood",
      slug: "coster-wood-120x60",
      shortDescription: "Collection effet bois naturel, format 120 × 60 cm, Made in India.",
      description:
        "Collection Coster Wood au rendu bois naturel, pensée pour apporter une atmosphère chaleureuse et élégante aux espaces intérieurs.",
      reference: null,
      categoryId: "carrelage",
      subcategoryId: "carrelage-effet-bois",
      brand: null,
      material: null,
      finish: null,
      color: "Brun / bois naturel",
      format: "120 × 60 cm",
      originCountry: "Inde",
      madeIn: "Made in India",
      style: "Effet bois",
      usage: null,
      price: 79,
      oldPrice: null,
      discount: null,
      currency: "TND",
      unit: "m2",
      stock: null,
      stockStatus: "on_request",
      featured: true,
      newProduct: true,
      promotion: false,
      bestSeller: false,
      limitedStock: false,
      calculatorEnabled: true,
      lossPercent: 10,
      published: true,
      seoTitle: "Coster Wood 120x60 | Carrelage effet bois | STE SANI-ESSEF",
      seoDescription:
        "Coster Wood, format 120 × 60 cm, Made in India. Rendu bois naturel. Showroom STE SANI-ESSEF à Ksour Essef.",
      seoKeywords: "coster, wood, carrelage bois, effet bois, brun, 120x60, 120/60, inde, tunisie, mahdia",
      images: [
        { id: "cw1", url: "/images/coster-1.jpg", alt: "Coster Wood, rendu bois naturel", order: 0 },
        { id: "cw2", url: "/images/coster-2.jpg", alt: "Ambiance bois chaleureuse", order: 1 },
      ],
      variants: [],
      technical: [
        { label: "Format", value: "120 × 60 cm" },
        { label: "Origine", value: "Inde" },
        { label: "Pays", value: "Made in India" },
        { label: "Aspect", value: "Bois naturel" },
        { label: "Couleur", value: "Brun / bois naturel" },
        { label: "Style", value: "Effet bois" },
      ],
      extraInfo: "Référence, finition, matière, épaisseur et prix : information disponible sur demande.",
      views: 0,
      ordersCount: 0,
      createdAt: now,
      updatedAt: now,
    }),
  ];

  const projects: Project[] = [
    {
      id: "p-marbre",
      title: "Sol effet marbre",
      slug: "sol-effet-marbre",
      room: "Sol",
      description: "Une surface claire, presque minérale, qui agrandit la pièce et capte la lumière.",
      image: "/images/project-marbre.jpg",
      productIds: ["tekalu-crema"],
      published: true,
      sortOrder: 1,
      createdAt: now,
    },
    {
      id: "p-bois",
      title: "Sol effet bois",
      slug: "sol-effet-bois",
      room: "Sol",
      description: "Le rythme des lames bois réchauffe un intérieur contemporain sans alourdir les volumes.",
      image: "/images/project-bois.jpg",
      productIds: ["coster-wood", "semi-gres-28005"],
      published: true,
      sortOrder: 2,
      createdAt: now,
    },
    {
      id: "p-bain",
      title: "Salle de bain",
      slug: "salle-de-bain",
      room: "Salle de bain",
      description: "Matières claires, lignes simples, une salle d'eau pensée comme une pièce à vivre.",
      image: "/images/project-bain.jpg",
      productIds: ["tekalu-crema"],
      published: true,
      sortOrder: 3,
      createdAt: now,
    },
    {
      id: "p-salon",
      title: "Salon",
      slug: "salon",
      room: "Salon",
      description: "Un sol continu et une palette sable pour laisser le mobilier respirer.",
      image: "/images/project-salon.jpg",
      productIds: ["tekalu-crema"],
      published: true,
      sortOrder: 4,
      createdAt: now,
    },
    {
      id: "p-chambre",
      title: "Chambre",
      slug: "chambre",
      room: "Chambre",
      description: "Une atmosphère feutrée, portée par des tons bois et une lumière douce.",
      image: "/images/project-chambre.jpg",
      productIds: ["coster-wood"],
      published: true,
      sortOrder: 5,
      createdAt: now,
    },
    {
      id: "p-cuisine",
      title: "Cuisine",
      slug: "cuisine",
      room: "Cuisine",
      description: "Des surfaces faciles à vivre, dans une cuisine claire et graphique.",
      image: "/images/project-cuisine.jpg",
      productIds: ["tekalu-crema"],
      published: true,
      sortOrder: 6,
      createdAt: now,
    },
    {
      id: "p-terrasse",
      title: "Terrasse",
      slug: "terrasse",
      room: "Terrasse",
      description: "Prolonger l'intérieur vers l'extérieur avec une matière minérale.",
      image: "/images/project-terrasse.jpg",
      productIds: [],
      published: true,
      sortOrder: 7,
      createdAt: now,
    },
    {
      id: "p-entree",
      title: "Entrée",
      slug: "entree",
      room: "Entrée",
      description: "Le premier geste de la maison : un sol net, un ton chaud, une impression d'ordre.",
      image: "/images/project-entree.jpg",
      productIds: ["semi-gres-28005"],
      published: true,
      sortOrder: 8,
      createdAt: now,
    },
    {
      id: "p-mur",
      title: "Mur décoratif",
      slug: "mur-decoratif",
      room: "Mur",
      description: "Un mur traité comme une matière, pour structurer un salon ou une salle de bain.",
      image: "/images/project-mur.jpg",
      productIds: ["tekalu-crema"],
      published: true,
      sortOrder: 9,
      createdAt: now,
    },
  ];

  return {
    users: [
      {
        id: "admin",
        email: (process.env.ADMIN_EMAIL || "admin@sani-essef.tn").toLowerCase(),
        passwordHash,
        firstName: "Admin",
        lastName: "SANI-ESSEF",
        phone: "73 664 229",
        role: "admin",
        createdAt: now,
      },
    ],
    categories,
    subcategories,
    products,
    customers: [],
    orders: [],
    quotes: [],
    reviews: [],
    messages: [],
    projects,
    banners: [
      {
        id: "hero",
        title: "Donnez une nouvelle dimension à votre intérieur",
        subtitle: "Découvrez notre sélection de carrelages, revêtements et solutions pour embellir votre maison.",
        eyebrow: "Qualité • Design • Innovation • Rénovation",
        image: "/images/hero.jpg",
        ctaLabel: "Découvrir nos produits",
        ctaHref: "/shop",
        secondaryLabel: "Demander un devis",
        secondaryHref: "/quote",
        active: true,
        sortOrder: 1,
      },
    ],
    settings: {
      phone: "73 664 229",
      phoneTel: "+21673664229",
      gsm: "26 416 564",
      gsmTel: "+21626416564",
      whatsapp: "21626416564",
      address: "Route de Mahdia, Ksour Essef, Tunisie",
      hours: "08:00 - 18:30",
      days: "Ouvert 7/7",
      slogan: "Ça donne envie de rénover",
      facebook: "",
      instagram: "",
      email: "",
    },
  };
}
